job_parser/urls.py
from django.conf.urls import url
from views import job_post, content

urlpatterns = [
    url(r'^$', job_post.index, name='index'),
    url(r'^(?P<job_post_id>[0-9]+)/$', job_post.show, name='show'),
    url(r'^(?P<job_post_id>[0-9]+)/edit$', job_post.edit, name='edit'),
    url(r'^content/(?P<content_id>[0-9]+)$', content.single, name='single'),
    url(r'^content/(?P<content_id>[0-9]+)/edit$', content.edit, name='content_edit'),
    url(r'^parse$', job_post.fetch, name='job_post_fetch'),
]

job_searcher/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^job_post/', include('job_parser.urls')),
] + static.static(settings.STATIC_URL,
document_root=settings.STATIC_ROOT)

job_parser/models/company.py
from __future__ import unicode_literals

from django.db import models

class Company(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

job_parser/models/content.py
from __future__ import unicode_literals

from django.db import models

class Content(models.Model):
    text = models.CharField(max_length=1000)
    post_header = models.ForeignKey('PostHeader', on_delete=models.CASCADE)

job_parser/models/job_post.py
from __future__ import unicode_literals

from django.db import models

class JobPost(models.Model):
    url = models.CharField(max_length=200, unique=True)
    position = models.CharField(max_length=150)
    company = models.ForeignKey('Company', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.position

job_parser/models/post_header.py
from __future__ import unicode_literals

from django.db import models

class PostHeader(models.Model):
    orig_header = models.CharField(max_length=200)
    job_post = models.ForeignKey('JobPost')
    def __str__(self):
        return self.orig_header

job_parser/views/content.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from ..models import content as models

@csrf_exempt
def single(request, content_id):
    content = models.Content.objects.get(id=content_id)
    if request.method == 'DELETE':
        post = content.post_header.job_post
        return HttpResponseRedirect('/job_post/{}'.format(post.id))
    return HttpResponse('render(request, , context)')

def edit(request, content_id):
    content = models.Content.objects.get(id=content_id)
    if request.method == 'GET':
        context = {
            'text': content.text,
        }
        return HttpResponse(render(request, 'content/edit.html', context))

job_parser/views/job_post.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

import json

from ..builtin_scraper import scrape

from ..models import job_post as models

# Create your views here.
def index(request):
    posts = models.JobPost.objects.all().order_by('created_at')
    context = {
        'posts': posts,
    }
    return HttpResponse(render(request, 'job_post/index.html', context))

@csrf_exempt
def show(request, job_post_id):
    post = models.JobPost.objects.get(id=job_post_id)
    context = {
        'post': post,
        'headers': post.postheader_set.all(),
    }
    return HttpResponse(render(request, 'job_post/show.html', context))

def edit(request, job_post_id):
    post = models.JobPost.objects.get(id=job_post_id)
    context = {
        'post': post,
    }
    return HttpResponse(render(request, 'job_post/edit.html', context))

@csrf_exempt
def fetch(request):
    # pages = scrape()
    pages = models.JobPost.objects.get(id=4)
    context = {
        'pages': pages,
    }
    if request.is_ajax():
        return HttpResponse(json.dumps(pages, default=dictify))
    return HttpResponse(render(request, 'job_post/fetch.html', context))

def dictify(post):
    if post:
        return {
            'url': post.url,
            'position': post.position,
            'company': post.company.name,
            'id': post.id
        }

job_searcher/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return(HttpResponse(render(request, 'index.html')))

job_parser/templates/content/edit.html
<textarea name="" id="" cols="30" rows="10">
  {{text}}
</textarea>
<a href="#" class='submit-content'>Submit</a>
<a href="#" class='cancel-content'>Cancel</a>

job_parser/templates/job_post/edit.html
<head>
  <script type='text/javascript' src='/static/js/models.js'></script>
  <script type='text/javascript' src='/static/js/jquery-2.2.3.min.js'></script>
  <script type='text/javascript' src='/static/js/ramda.min.js'></script>
</head>
<body>
  <form action="" id='edit-job-post'>
    <input type="text" value={{post.url}}><br>
    <input type="text" value={{post.position}}><br>
    <label for="">Headers<br></label>
    {% for header in post.postheader_set.all %}
      <p>{{header.orig_header}}</p>
      <!-- <input type='text' value={{header.orig_header}}><br> -->
      {% for content in header.content_set.all %}
        <div class='content {{content.id}}'>
          <p>{{content.text}}</p>
          <a class='delete-content' href='content/{{content.id}}'>Delete</a>
          <a class='edit-content' href='content/{{content.id}}'>Edit</a>
        </div>
      {% endfor %}
    {% endfor %}
    <input type="submit">
  </form>
</body>

<script type='text/javascript'>
  (function(){
    var $form = $('#edit-job-post');
    var {JobPost, Content} = import_models();

    function extractFromContent(e) {
      e.preventDefault();
      var parent = e.target.parentElement,
          id = parent.classList[1];
      return {id};
    }

    function _delete(data) {
      var promise = JobPost.deleteContent(data);
      // searching the DOM not ideal
      promise.done(function(){
        $('.content.'+data.id).toggle();
      });
    }

    function _edit(data) {
      var $content = $('.content.'+data.id),
          text = $content.find('p').text(),
          promise;


      if ($content.find('textarea').length) {
        $content.children().toggle();
      }
      else {
        $content.children().toggle();
        Content.getEditable(data.id).done(function(textarea){
          $content.append(textarea);
        });
      }
    }

    function _submit(data) {
      var $content = $('.content.'+data.id),
          text = $content.find('textarea').text(),
          promise;

      promise = Content.update(data.id, text);
      promise.done(_edit.bind(null, data));
    }

    function _cancel(data) {
      var $content = $('.content.'+data.id);
      $content.children().toggle();
    }

    $form.on('click', '.delete-content', 
        R.compose(_delete, extractFromContent));

    $form.on('click', '.edit-content',
        R.compose(_edit, extractFromContent));

    $form.on('click', '.cancel-content',
        R.compose(_cancel, extractFromContent));

    $form.on('click', '.submit-content',
        R.compose(_submit, extractFromContent));
  }())
</script>

job_parser/templates/job_post/fetch.html
<h3>Fetching more jobs</h3>
<a href="/job_post">Return To Job Posts</a>

<ul>
{% for post in pages %}
  {% if post %}
  <li>
    <a href='{{post.id}}'>
      {{post.position}}
    </a>
  </li>
  {% endif %}
{% endfor %}
</ul>

job_parser/templates/job_post/index.html
<head>
  <script type='text/javascript' src='/static/js/models.js'></script>
  <script type='text/javascript' src='/static/js/jquery-2.2.3.min.js'></script>
  <script type='text/javascript' src='/static/js/ramda.min.js'></script>
</head>
<h1>Builtin Chicago Job Posts</h1>
<form action="parse" method='post'>
  <input type="submit" value='Get More Posts'>
</form>
<ul>
  {% for post in posts %}
    <li>
      <a href='{{post.id}}'>
        {{post.position}}
      </a>
    </li>
  {% endfor %}
</ul>
<script src='../../static/js/job_post/app.js' type='text/javascript'></script>

job_parser/templates/job_post/show.html
<h1>{{post.position}}</h1>
<h2>{{post.company.name}}</h2>
<a href='edit'>edit</a>
<a href='{{post.url}}'>post</a>
{% for h in headers %}
  <h3>{{h}}</h3>
  {% for c in h.content_set.all %}
    <p>{{c.text}}</p>
  {% endfor%}
{% endfor%}

job_searcher/templates/index.html
<h1>Job Parser App</h1>
<a href="/job_post">Main</a>